---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: k8s-env-repo
  namespace: argocd
spec:
  backendType: systemManager
  region: us-east-2
  data:
    - key: github_token
      name: password
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/part-of: argocd
        argocd.argoproj.io/secret-type: repository
    stringData:
      type: git
      url: https://github.com/planetarium/9c-infra
      username: libplanet
