apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../common/argocd
  - bootstrap.yaml
  - argocd-ingress.yaml
  - argocd-secrets.yaml
patchesStrategicMerge:
  - argocd-cm.yaml
patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: kubernetes-external-secrets
    patch: |-
      - op: add
        path: /spec/source/helm/values
        value: |-
          env:
            AWS_REGION: ''
            AWS_DEFAULT_REGION: ''
            VAULT_ADDR: ''
          securityContext:
            fsGroup: 65534
          serviceAccount:
            name: 9c-2023q1-preview-external-secrets
            annotations:
              eks.amazonaws.com/role-arn: arn:aws:iam::838612679705:role/eks-9c-2023q1-preview-external-secrets
