{{ if .Values.useExternalSecret }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: slack-token
  namespace: {{ $.Chart.Name }}
spec:
  backendType: secretsManager
  dataFrom:
    - {{ $.Chart.Name }}/slack-token
{{ else }}
apiVersion: v1
kind: Secret
metadata:
  name: slack-token
  namespace: {{ $.Chart.Name }}
stringData:
  slack-token: {{ .Values.slackToken }}
type: Opaque
{{ end }}
