clusterName: 9c-internal-v2
logLevel: debug
appProtocolVersion: 
  200020/54684Ac4ee5B933e72144C4968BEa26056880d71/MEQCIFp.SfFaK3PCLyqwN28j4qptXqWnToggZOQTLAFly5I3AiBr.824.h8.VwjhVwz5zulv7pKqBLARAP6pYQGPd6js+A==/ZHU4OmxhdW5jaGVydTQyOjEvODBkYjhmNDU1MTU5ODNiYWY5YjFkYjEwMDZmOWIwMjRjNWIzMWU1NnU2OnBsYXllcnU0MjoxL2M2NjUyYTEzNmQ1ZDZkMmVhOGQyNmFmNmM0M2Y1MTg5ZmJiYzYxZGN1OTp0aW1lc3RhbXB1MTA6MjAyMy0wNS0wNGU=
genesisBlockPath: https://release.nine-chronicles.com/genesis-block-9c-main
trustedAppProtocolVersionSigner: 02529a61b9002ba8f21c858224234af971e962cac9bd7e6b365e71e125c6463478
peerStrings:
- 033369e95dbfd970dd9a7b4df31dcf5004d7cfd63289d26cc42bbdd01e25675b6f,9c-internal-tcp.planetarium.dev,31234
iceServers:
- turn://0ed3e48007413e7c2e638f13ddd75ad272c6c507e081bd76a75e4b7adc86c9af:0apejou+ycZFfwtREeXFKdfLj2gCclKzz5ZJ49Cmy6I=@turn-us.planetarium.dev:3478
networkType: Internal
consensusType: pbft
useExternalSecret: true
slackToken: ''
slackWebHookUrl: ''
snapshot:
  resetSnapshot: true
  slackChannel: 9c-internal
  image: 
    planetariumhq/ninechronicles-snapshot:git-fc194ebdc47ec4ebe14f97f5ea01ff97b0a276d6
  cfDistributionId: ''
  aws_access_key_id: ''
  aws_secret_access_key: ''
volumeReclaimPolicy: Retain
validator:
  count: 4
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    tag: git-3091462be6e5ce26d72fbe3d773c80d9c7d2ed3f
  consensusSeedStrings:
  - 033369e95dbfd970dd9a7b4df31dcf5004d7cfd63289d26cc42bbdd01e25675b6f,tcp-seed-1,31235
  hosts:
  - "9c-internal-validator-1.nine-chronicles.com"
  - "9c-internal-validator-2.nine-chronicles.com"
  - "9c-internal-validator-3.nine-chronicles.com"
  - "9c-internal-validator-4.nine-chronicles.com"
  ports:
    headless: 31234
    graphql: 80
    gossip: 6000
  extraArgs: []
  privateKeys: []
  storage:
    data: 500Gi
  env: []
  resources:
    requests:
      cpu: 1
      memory: 12Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
seed:
  count: 1
  useTurnServer: false
  image:
    repository: planetariumhq/libplanet-seed
    pullPolicy: Always
    tag: git-22bed8ef41ab09258e6404462ec8e07cd038d089
  hosts:
  - "9c-internal-tcp.planetarium.dev"
  ports:
    node: 31234
    gossip: 31235
    graphql: 31237
  workerCount: 1000
  extraArgs: []
  privateKeys: []
  env: []
  resources:
    requests:
      cpu: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
miner:
  count: 1
  useTurnServer: true
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    tag: git-3091462be6e5ce26d72fbe3d773c80d9c7d2ed3f
  hosts: []
  ports:
    headless: 31234
    graphql: 80
  extraArgs: []
  privateKeys: []
  storage:
    data: 500Gi
  env: []
  resources:
    requests:
      cpu: 1
      memory: 8Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
remoteHeadless:
  count: 1
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    tag: git-3091462be6e5ce26d72fbe3d773c80d9c7d2ed3f
  extraArgs: []
  useTurnServer: false
  hosts:
  - "9c-internal-rpc-1.nine-chronicles.com"
  ports:
    headless: 31234
    graphql: 80
    rpc: 31238
  storage:
    data: 500Gi
  resources:
    requests:
      cpu: 1
      memory: 12Gi
  nodeSelector:
    beta.kubernetes.io/os: linux
  tolerations: []
  affinity: {}
dataProvider:
  enabled: true
  render: true
  storage:
    data: 1000Gi
    log: 4Gi
  image:
    repository: planetariumhq/ninechronicles-dataprovider
    pullPolicy: Always
    tag: git-cafc35322f20849854d9104541f5478162b2c194
  db:
    storage: 1000Gi
    database: ''
    connectionString: ''
    host: ''
    port: 3306
    user: user
    password: ''
explorer:
  image:
    repository: planetariumhq/ninechronicles-headless
    pullPolicy: Always
    tag: git-3091462be6e5ce26d72fbe3d773c80d9c7d2ed3f
  extraArgs: []
  useTurnServer: true
  hosts: []
  ports:
    headless: 31234
    graphql: 80
  storage:
    data: 500Gi
    log: 4Gi
  resources:
    requests:
      cpu: 1
      memory: 4Gi
  nodeSelector:
    beta.kubernetes.io/os: linux
  tolerations: []
  affinity: {}
marketService:
  enabled: true
  image:
    repository: planetariumhq/market-service
    pullPolicy: Always
    tag: git-167c1345890c1fee72f4771ec2c0d5f48452fe81
  db:
    size: 1Gi
